application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /(update-line-status|clear-old-registrations|update-weekend-status)
  script: cron_receiver.app
  login: admin
  auth_fail_action: unauthorized

- url: /(get-line-status|register-for-alerts|get-weekend-status)
  script: clients_controller.app

- url: /(find-affected-users|gae_python_gcm/send_request)
  script: tasks_controller.app

- url: /.*
  script: clients_controller.app


libraries:
- name: django
  version: "1.2"
  # required for GCM module